### PR TITLE
Generalize install-julia.sh

### PR DESCRIPTION
**Pull request by fredrikekre**
Generalize `install-julia.sh` to take any valid version number.

### CODE REVIEW

**Comment by tpapp** [comment]
Thanks. The build script breakage is unrelated and I will look into it.

**Comment by fredrikekre** [comment]
It is probably just because `DOCKER_USER` is not specified due to this PR coming from a fork?

**Comment by fredrikekre** [comment]
Btw, I am getting this error: https://github.com/fredrikekre/ConstLab.jl/pull/2#issuecomment-557256420 which is kinda strange, because the same image is used for PGFPlotsX, right?

Edit: nvm, I was missing https://github.com/KristofferC/PGFPlotsX.jl/blob/1b672f54c5e92d4951a184d1d9b8d30e4c542f21/test/runtests.jl#L9-L11

**Comment by tpapp** [comment]
That's probably it. Merging this, then I will clean up a bit.

**Pull request merged**
